(:mallet-config
 (:extends :all)
 (:ignore "/tests/fixtures/" "/*.lisp")
 (:enable :cyclomatic-complexity)
 (:enable :consecutive-blank-lines :max 2)
 (:disable :line-length)
 (:disable :function-length)
 (:disable :missing-otherwise)
 (:disable :special-variable-naming)
 (:disable :constant-naming)
 (:for-paths ("/src/parser.lisp")
  (:disable :unused-local-nicknames))
 (:for-paths ("src/main.lisp")
  (:enable :cyclomatic-complexity :max 25))
 (:for-paths ("tests/rules/text-formatting-test.lisp")
  (:disable :consecutive-blank-lines)))
