(defpackage #:mallet/tests/readme-init-section
  (:use #:cl #:rove))
(in-package #:mallet/tests/readme-init-section)

(defun readme-content ()
  "Read and return the content of README.md."
  (let ((path (merge-pathnames "README.md"
                               (asdf:system-source-directory "mallet"))))
    (uiop:read-file-string path)))

(defun find-adopting-section (content)
  "Extract the 'Adopting Mallet' section from CONTENT, up to the next ## heading.
   Returns NIL if the section does not exist."
  (let ((start (search "## Adopting Mallet" content)))
    (when start
      (let ((next-h2 (search (format nil "~%## ") content :start2 (1+ start))))
        (subseq content start (or next-h2 (length content)))))))

(defun near-p (anchor needle haystack &key (window 200))
  "Return non-NIL if NEEDLE appears within WINDOW characters of ANCHOR in HAYSTACK."
  (let ((anchor-pos (search anchor haystack)))
    (when anchor-pos
      (let* ((start (max 0 (- anchor-pos window)))
             (end (min (length haystack) (+ anchor-pos (length anchor) window))))
        (search needle haystack :start2 start :end2 end)))))

;;; Gate 1: README.md contains a section about adopting Mallet on an existing
;;;         project in which the literal string --init appears.

(deftest readme-has-adopting-mallet-section
  (testing "README.md contains a section heading for adopting Mallet on an existing project"
    (let ((section (find-adopting-section (readme-content))))
      (ok section
          "README.md must contain an 'Adopting Mallet' section")))
  (testing "The adopting section contains the literal string --init"
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (search "--init" section))
          "The adopting section must contain '--init'")))
  (testing "The adopting section specifically addresses adoption on an existing project or codebase"
    ;; Fails if 'existing' only appears in 'existing config' (from the --force description)
    ;; but never in the context of an existing project or codebase being adopted.
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section
               (or (search "existing project" section)
                   (search "existing codebase" section)
                   (search "existing code base" section)))
          "The adopting section must mention 'existing project' or 'existing codebase', not just 'existing config'"))))

;;; Gate 2: That section shows an example invocation that generates a
;;;         .mallet.lisp and mentions the --force flag.

(deftest readme-adopting-section-shows-mallet-init-example
  (testing "The adopting section shows a 'mallet --init' example invocation"
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (search "mallet --init" section))
          "The adopting section must show a 'mallet --init' command")))
  (testing "The adopting section mentions .mallet.lisp as the generated output"
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (search ".mallet.lisp" section))
          "The adopting section must mention '.mallet.lisp'")))
  (testing "The 'mallet --init' invocation and .mallet.lisp appear together (within 200 chars)"
    ;; Fails if .mallet.lisp is only mentioned in unrelated prose far from the example command.
    ;; The correct implementation shows the example generating .mallet.lisp nearby.
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (near-p "mallet --init" ".mallet.lisp" section))
          "The adopting section must tie the 'mallet --init' invocation to generating '.mallet.lisp'")))
  (testing "The section explains that 'mallet --init' generates .mallet.lisp"
    ;; Fails if .mallet.lisp is mentioned but 'generat' only appears in a different context
    ;; (e.g. '--force overwrites generated defaults') rather than describing .mallet.lisp
    ;; as the output that is generated.
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (near-p ".mallet.lisp" "generat" section :window 100))
          "The adopting section must use 'generat*' within 100 chars of '.mallet.lisp' to explain it is generated by the invocation")))
  (testing "The 'mallet --init' command appears at an earlier character position than '.mallet.lisp'"
    ;; Fails for the causality-inverted form 'after creating .mallet.lisp, run mallet --init'
    ;; where .mallet.lisp precedes mallet --init in the text.
    ;; The correct form is 'run mallet --init to generate .mallet.lisp'.
    (let* ((content (readme-content))
           (section (find-adopting-section content))
           (init-pos (and section (search "mallet --init" section)))
           (lisp-pos (and section (search ".mallet.lisp" section))))
      (ok (and init-pos lisp-pos (< init-pos lisp-pos))
          "The 'mallet --init' command must appear before '.mallet.lisp' in the section text"))))

(deftest readme-adopting-section-mentions-force-flag
  (testing "The adopting section mentions --force for overwriting an existing config"
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (search "--force" section))
          "The adopting section must mention '--force' for overwriting existing config")))
  (testing "--force is described as overwriting an existing config (within 200 chars of 'overwrite')"
    ;; Fails if --force is mentioned as generic troubleshooting without explaining it overwrites.
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (near-p "--force" "overwrite" section))
          "The adopting section must explain '--force' in terms of overwriting an existing config")))
  (testing "--force is specifically about overwriting an existing config, not arbitrary output"
    ;; Fails if '--force' says 'overwrites generated defaults' rather than mentioning an existing config.
    ;; The 'existing' here must appear in context of what --force overwrites, not just elsewhere.
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section (near-p "--force" "existing" section :window 150))
          "The adopting section must describe '--force' as overwriting an existing config (not just generated output)")))
  (testing "--force description names the config file or 'config' as what is overwritten"
    ;; Fails for 'use --force to overwrite existing generated output' — that phrasing satisfies
    ;; the nearby 'overwrite' and 'existing' checks above, but never identifies what is overwritten.
    ;; The correct form names '.mallet.lisp' or 'config' near '--force'.
    (let* ((content (readme-content))
           (section (find-adopting-section content)))
      (ok (and section
               (or (near-p "--force" ".mallet.lisp" section :window 150)
                   (near-p "--force" "config" section :window 150)))
          "The --force description must name the config file ('.mallet.lisp' or 'config') as what is overwritten"))))

;;; Structural check: section appears before Configuration

(deftest readme-adopting-section-placed-before-configuration
  (testing "The adopting section appears before the Configuration section"
    (let* ((content (readme-content))
           (adopt-pos (search "## Adopting Mallet" content))
           (config-pos (search "## Configuration" content)))
      (ok adopt-pos
          "README.md must contain an 'Adopting Mallet' section heading")
      (ok config-pos
          "README.md must contain a 'Configuration' section heading")
      (ok (and adopt-pos config-pos (< adopt-pos config-pos))
          "The adopting section must appear before the Configuration section"))))
