name: CI

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        lisp:
          - sbcl-bin
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          mkdir -p "$HOME/.local/bin"
          printf '#!/bin/sh\nexec ros run -- "$@"\n' > "$HOME/.local/bin/sbcl"
          chmod u+x "$HOME/.local/bin/sbcl"

      - name: Install Qlot
        run: |
          ros install fukamachi/qlot
          ros install fukamachi/archive/fix/tar-symlink-entry
          echo "$HOME/.roswell/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          qlot install --no-deps
          qlot exec ros -e '(ql:quickload :malo/tests)'

      - name: Run test suite
        run: |
          make test

      - name: Build binary
        run: |
          make build
          ./malo --version
